name: GaleriaArtistasCuritibanos
options:
  bundleIdPrefix: br.pucpr.lucasstopinski
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

targets:
  GaleriaArtistasCuritibanos:
    type: application
    platform: iOS
    sources:
      - path: GaleriaArtistasCuritibanos
    info:
      path: GaleriaArtistasCuritibanos/Info.plist
      properties:
        CFBundleDisplayName: Galeria CWB
        UILaunchScreen:
          UIColorName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.pucpr.lucasstopinski.GaleriaArtistasCuritibanos
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: NO
